#version: '3'
#services:
#  mysql:
#    image: 'mysql:8.0'
#    ports:
#      - 3310:3310
#    environment:
#      - MYSQL_ROOT_PASSWORD=root
#      - MYSQL_DATABASE=mysql
#    volumes:
#      - ./db/sql/ini:/docker-entrypoint-initdb.d
#  redis:
#    image: 'redis:7.4.2'
#    ports:
#      - 6379:6379
#  consul:
#    image: "hashicorp/consul:latest"
#    ports:
#      - "8500:8500"
#    environment:
#      CONSUL_BIND_INTERFACE: eth0
#  # Jaeger
#  jaeger-all-in-one:
#    container_name: jaeger-all-in-one
#    image: jaegertracing/all-in-one:1.65.0
#    ports:
#      - "16686:16686"
#      - "4317:4317"
#      - "4318:4318"
#  prometheus:
#    image: prom/prometheus:v3.1.0
#    volumes:
#      - ./deploy/config/prometheus.yml:/etc/prometheus/prometheus.yml
#    command:
#      - "--config.file=/etc/prometheus/prometheus.yml"
#    ports:
#      - "9090:9090"
#  etcd:
#    image: docker.io/bitnami/etcd:3.5
#    environment:
#      - ALLOW_NONE_AUTHENTICATION=yes
#    ports:
#      - 2379:2379
#      - 2380:2380
#  nats:
#    image: nats:2.9.24
#    ports:
#      - "4222:4222"
#      - "8222:8222"
#
#  grafana:
#    image: grafana/grafana:11.4.0
#    environment:
#      - GF_AUTH_ANONYMOUS_ENABLED=true
#      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
#      - GF_AUTH_DISABLE_LOGIN_FORM=true
#    ports:
#      - "3000:3000"
#
#  loki:
#    image: grafana/loki:2.9.2
#    volumes:
#      - ./deploy/config/loki.yml:/etc/loki/local-config.yaml
#    command: -config.file=/etc/loki/local-config.yaml
#    ports:
#      - "3100:3100"
#
#  promtail:
#    image: grafana/promtail:2.9.2
#    volumes:
#      - ./deploy/config/promtail.yml:/etc/promtail/config.yml
#      - ./app/frontend/log:/logs/frontend
#    command: -config.file=/etc/promtail/config.yml
