version: '3'
services:
  mysql:
    image: 'mysql:8.0'
    ports:
      - 3310:3306
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=mysql
  redis:
    image: 'redis:latest'
    ports:
      - 6379:6379
